// examples/vue/src/App.vue
<script setup lang="ts">
import { modal, wallet } from '@bestinslot/wallet-kit'
import { useNetwork } from '@bestinslot/wallet-kit/vue'
import { ref } from 'vue'

const network = useNetwork()
const session = ref(wallet.getSession())

async function connect() {
  try {
    await modal.connect()
    session.value = wallet.getSession()
  } catch (e) {
    console.error('Connection failed:', e)
  }
}

function disconnect() {
  wallet.disconnect()
  session.value = wallet.getSession()
}
</script>

<template>
  <main>
    <h1>BiS Wallet Kit — Vue</h1>
    <button type="button" @click="connect">Connect</button>
    <button type="button" @click="disconnect">Disconnect</button>
    <select v-model="network">
      <option value="mainnet">mainnet</option>
      <option value="testnet">testnet</option>
      <option value="signet">signet</option>
    </select>
    <pre>{{ session ? JSON.stringify(session, null, 2) : 'Not connected' }}</pre>
  </main>
</template>

// examples/react/src/App.tsx
import type { BISNetwork } from '@bestinslot/wallet-kit/react'
import { modal, wallet } from '@bestinslot/wallet-kit'
import { useWallet } from '@bestinslot/wallet-kit/react'

export function App() {
  const { session, network, setNetwork, refresh } = useWallet()

  async function connect() {
    try {
      await modal.connect()
      refresh()
    } catch (e) {
      console.error('Connection failed:', e)
    }
  }

  function disconnect() {
    wallet.disconnect()
    refresh()
  }

  return (
    <main>
      <h1>BiS Wallet Kit — React</h1>
      <button type="button" onClick={connect}>
        Connect
      </button>
      <button type="button" onClick={disconnect}>
        Disconnect
      </button>
      <select value={network} onChange={e => setNetwork(e.target.value as BISNetwork)}>
        <option value="mainnet">mainnet</option>
        <option value="testnet">testnet</option>
        <option value="signet">signet</option>
      </select>
      <pre>{session ? JSON.stringify(session, null, 2) : 'Not connected'}</pre>
    </main>
  )
}
